<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<?php foreach ($form as $element): ?>
	<div class="form-group">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
			<label><?php echo $this->formLabel($element) ?></label>
		<?php endif ?>
		<?php if ($element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formButton($element) ?>
		<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
			<?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
		<?php elseif ($element instanceof DoctrineModule\Form\Element\ObjectSelect): ?>
            <?php echo $this->formSelect($element) . $this->formElementErrors($element) ?>
		<?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
            <?php echo $this->formTextarea($element) . $this->formElementErrors($element) ?>
		<?php else: ?>
            <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
		<?php endif ?>
	</div>
<?php endforeach ?>
<?php if ($this->redirect): ?>
	<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?php echo $this->form()->closeTag() ?>