<?php
$typeList = array('new', 'open', 'closed');
?>
<a href="<?= $this->url('zfc-ticketsystem', array('action' => 'new')) ?>" class="btn btn-primary"><i class="fa fa-plus"></i> new ticket</a>
<div class="clearfix"></div>
<div class="table-responsive margin-top-10">
	<table class="table table-bordered table-hover">
		<tr>
			<th>Subject</th>
			<th>Type</th>
			<th>LastEdit</th>
			<th>Created</th>
			<th>Option</th>
		</tr>
		<?php foreach($this->ticketList as $ticketSubject): ?>
			<tr>
				<th><?= $ticketSubject->getSubject() ?></th>
				<th><?= $typeList[$ticketSubject->getType()] ?></th>
				<th><?= $ticketSubject->getLastEdit()->format('d.m.Y H:i') ?></th>
				<th><?= $ticketSubject->getCreated()->format('d.m.Y H:i') ?></th>
				<th><a href="<?= $this->url('zfc-ticketsystem', array('id' => $ticketSubject->getTicketid(), 'action' => 'view' )) ?>" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i> View</a></th>
			</tr>
		<?php endforeach ?>
	</table>
</div>