sudo: false

language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly

before_script:
  - composer selfupdate
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
