language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer update --prefer-source --dev

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
