sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

allow_failures:
  - php: nightly
  - php: hhvm

before_script:
  - composer selfupdate
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
